# Generated by Django 6.0.5 on 2026-06-03 11:42

import apps.alerts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityalert',
            name='dismissed_by_users',
            field=models.ManyToManyField(blank=True, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityalert',
            name='expires_at',
            field=models.DateTimeField(default=apps.alerts.models.default_expires_at),
        ),
        migrations.AddField(
            model_name='communityalert',
            name='read_by_users',
            field=models.ManyToManyField(blank=True, related_name='read_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communityalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.communityalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('alert', 'user')},
            },
        ),
    ]
