# Generated by Django 6.0.5 on 2026-06-03 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('weekly_report', 'Weekly Report'), ('recommendation', 'Daily Recommendation'), ('alert_notification', 'Alert Notification'), ('report_export', 'Report Export')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generated', 'Generated'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('emailed', 'Emailed'), ('exported', 'Exported')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.weeklyreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
